version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3366:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=pass1919
      - MYSQL_USER=tata1919
      - MYSQL_DATABASE=app